### ISSUE TITLE
Import error using import_hypervisor.py

### ISSUE THREAD

**Issue by danilochilene** [julcollas/django-vsphere#2]
Hello,
I'm trying import a hypervisor using import_hypervisor.py

In [2]: server = VIServer()
In [3]: server.connect("10.1.1.1", "monitor", "monitor")
In [4]: create_full_hypervisor(server, 'Datacenter', 'Annotation')
TypeError: create_full_hypervisor() takes exactly 4 arguments (3 given)

Checking the function create_full_hypervisor it takes 4 arguments.
def create_full_hypervisor(server, datacenter, note, dhm_vm)

I tried get rid of dhm_vm variable and got the error below:
IntegrityError: UNIQUE constraint failed: vsphere_hypervisor.name

Can you give me an example of how import a hypervisor or I did something wrong?

**Comment by julcollas** [comment]
Can you give me more detail ?
Did you try to import twice the same Hypervisor ? Or two hypervisors with the same name ?

**Comment by danilochilene** [comment]
Clean database.

Result of pip freeze
Django==1.7
argparse==1.2.1
django-tastypie==0.12.1
django-vsphere==0.7
pysphere==0.1.7
python-dateutil==2.4.2
python-mimeparse==0.1.4
six==1.9.0
wsgiref==0.1.2

(vsphere)~/l/vmware ❯❯❯ export DJANGO_SETTINGS_MODULE="vmware.settings"
(vsphere)~/l/vmware ❯❯❯ python import_hypervisor.py
"hostname" option is missing
Usage: import_hypervisor.py [options]

Options:
  -h, --help            show this help message and exit
  -H HOSTNAME, --hostname=HOSTNAME
                        Host name, IP Address - mandatory
  -u USER, --user=USER  User name [default: root]
  -d DATACENTER, --datacenter=DATACENTER
                        Datacenter [default: ]
  -p PASSWORD, --password=PASSWORD
                        Password to connect [default: ]
  -a ANOTATION, --anotation=ANOTATION
                        Hypervisor Note [default: ](vsphere)~/l/vmware ❯❯❯ python import_hypervisor.py -H 10.1.1.1 -u monitor -pmonitor -d DATACENTER
Traceback (most recent call last):
  File "import_hypervisor.py", line 466, in <module>
    create_full_hypervisor(server, datacenter, note)
TypeError: create_full_hypervisor() takes exactly 4 arguments (3 given)

**Comment by julcollas** [comment]
Oops :)
I committed a new import script (a4ed0bdb2463fe8c64440d24e61149b79c88c68d) , can you try with this new one ?
Thanks

**Comment by danilochilene** [comment]
Hey,

I tried the same change you did and got this:

vsphere)~/l/vmware ❯❯❯ python import_hypervisor.py -H 10.1.1.1 -u monitor -p monitor -d DATACENTER
Traceback (most recent call last):
  File "import_hypervisor.py", line 464, in <module>
    create_full_hypervisor(server, datacenter, note)
  File "import_hypervisor.py", line 363, in create_full_hypervisor
    create_datastore(ds, hypervisor)
  File "import_hypervisor.py", line 264, in create_datastore
    d.save()
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 919, in execute_sql
    for sql, params in self.as_sql():
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 877, in as_sql
    for obj in self.query.objs
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1722, in get_db_prep_save
    return self.related_field.get_db_prep_save(value, connection=connection)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1668, in related_field
    return self.foreign_related_fields[0]
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1426, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1413, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1406, in resolve_related_fields
    else self.rel.to._meta.get_field_by_name(to_field_name)[0])
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/options.py", line 416, in get_field_by_name
    cache = self.init_name_map()
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/options.py", line 445, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/options.py", line 563, in get_all_related_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/db/models/options.py", line 577, in _fill_related_many_to_many_cache
    for klass in self.apps.get_models():
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(_args, *_kwds)
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by danilochilene** [comment]
I think now is Django 1.7 related http://stackoverflow.com/questions/25680803/django-1-7-upgrade-error-appregistrynotready-models-arent-loaded-yet

**Comment by julcollas** [comment]
Can you try with a Django 1.6 to validate ?

**Comment by danilochilene** [comment]
Got a new error.

Traceback (most recent call last):
  File "import_hypervisor.py", line 466, in <module>
    create_full_hypervisor(server, datacenter, note)
  File "import_hypervisor.py", line 392, in create_full_hypervisor
    GUESTS = get_guests(server)
  File "import_hypervisor.py", line 172, in get_guests
    annotation = vm.properties.config.annotation
  File "/home/danilochilene/.envs/vsphere/local/lib/python2.7/site-packages/pysphere/vi_property.py", line 74, in **getattr**
    raise AttributeError("object has not attribute %s" % name)
AttributeError: object has not attribute annotation

Still debugging it.

**Comment by danilochilene** [comment]
I worked after I changed annotation = vm.properties.config.annotation to annotation = '' (with Django 1.7)

**Comment by julcollas** [comment]
Ok, thanks for that. In which version of ESXi are you ?

**Comment by danilochilene** [comment]
5.5

**Comment by danilochilene** [comment]
Going close this since I got it working with Django 1.7, thanks!

**Comment by julcollas** [comment]
Ok thanks. Let me know. Regards.
